name: Update PR Count Badge

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  pr-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get PR counts
        run: |
          # Total PRs
          TOTAL=$(gh search prs --author suprateem-ux --json number --limit 1000 | jq length)

          # Merged PRs
          MERGED=$(gh search prs --author suprateem-ux --is merged --json number --limit 1000 | jq length)

          # Save two separate badge JSON files
          echo "{ \"label\": \"PRs\", \"message\": \"$TOTAL\", \"color\": \"blue\" }" > pr-badge.json
          echo "{ \"label\": \"Merged PRs\", \"message\": \"$MERGED\", \"color\": \"green\" }" > merged-pr-badge.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit badge data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pr-badge.json merged-pr-badge.json
          git commit -m "Update PR count badges" || echo "No changes to commit"
          git push
